FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests -pl producer -am

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/producer/target/producer-*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]